import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import HomePage from "./Home";
import Contact from "./Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AtlasLawncare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <HomePage />
      </main>
    </>
  );
}
